/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddOrderItemsToBanquetRequest : Request for add order items to banquet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOrderItemsToBanquetRequest {
    /// Banquet ID.
    #[serde(rename = "reserveId")]
    pub reserve_id: uuid::Uuid,
    /// Organization ID.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    /// Order items (may include ProductOrderItem or CompoundOrderItem).
    #[serde(rename = "items")]
    pub items: Vec<models::RequestCreateOrderItem>,
    /// Combos.   > Allowed from version `7.6.1`.
    #[serde(
        rename = "combos",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub combos: Option<Option<Vec<models::RequestCreateOrderCombo>>>,
}

impl AddOrderItemsToBanquetRequest {
    /// Request for add order items to banquet.
    pub fn new(
        reserve_id: uuid::Uuid,
        organization_id: uuid::Uuid,
        items: Vec<models::RequestCreateOrderItem>,
    ) -> AddOrderItemsToBanquetRequest {
        AddOrderItemsToBanquetRequest {
            reserve_id,
            organization_id,
            items,
            combos: None,
        }
    }
}
