/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllowedItemWithDuration : Suitable terminal group with delivery duration and other parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllowedItemWithDuration {
    /// Terminal group ID.                Can be obtained by `/api/1/terminal_groups` operation.
    #[serde(rename = "terminalGroupId")]
    pub terminal_group_id: uuid::Uuid,
    /// Organization ID.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    /// Delivery duration in minutes.
    #[serde(rename = "deliveryDurationInMinutes")]
    pub delivery_duration_in_minutes: i64,
    /// Delivery zone name which this TerminalGroupId belongs to.
    #[serde(rename = "zone", deserialize_with = "Option::deserialize")]
    pub zone: Option<String>,
    /// Link to \"delivery service payment\".
    #[serde(
        rename = "deliveryServiceProductId",
        deserialize_with = "Option::deserialize"
    )]
    pub delivery_service_product_id: Option<uuid::Uuid>,
}

impl AllowedItemWithDuration {
    /// Suitable terminal group with delivery duration and other parameters.
    pub fn new(
        terminal_group_id: uuid::Uuid,
        organization_id: uuid::Uuid,
        delivery_duration_in_minutes: i64,
        zone: Option<String>,
        delivery_service_product_id: Option<uuid::Uuid>,
    ) -> AllowedItemWithDuration {
        AllowedItemWithDuration {
            terminal_group_id,
            organization_id,
            delivery_duration_in_minutes,
            zone,
            delivery_service_product_id,
        }
    }
}
