/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CourierLocationsByTimeOffsetRequest : Request for coordinates history of drivers in OrganizationIds organizations.  If driver coordinates were recorded in server storage within interval:   [\"current server time\" - OffsetInSeconds, \"current server time\"),  driver and their coordinates will be retrieved.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourierLocationsByTimeOffsetRequest {
    /// List of organizations for drivers coordinates of which will be retrieved.
    #[serde(rename = "organizationIds")]
    pub organization_ids: Vec<uuid::Uuid>,
    /// Interval in seconds from current server time.   If driver coordinates were recorded in server storage   within interval: (\"current server time\" - *OffsetInSeconds*, \"current server time\"],  driver and their coordinates will be retrieved.
    #[serde(
        rename = "offsetInSeconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub offset_in_seconds: Option<Option<i32>>,
}

impl CourierLocationsByTimeOffsetRequest {
    /// Request for coordinates history of drivers in OrganizationIds organizations.  If driver coordinates were recorded in server storage within interval:   [\"current server time\" - OffsetInSeconds, \"current server time\"),  driver and their coordinates will be retrieved.
    pub fn new(organization_ids: Vec<uuid::Uuid>) -> CourierLocationsByTimeOffsetRequest {
        CourierLocationsByTimeOffsetRequest {
            organization_ids,
            offset_in_seconds: None,
        }
    }
}
