/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeliveryOrderType : Order type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryOrderType {
    /// Order type ID in RMS.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Order type name.
    #[serde(rename = "name")]
    pub name: String,
    /// Service type.
    #[serde(rename = "orderServiceType")]
    pub order_service_type: models::DeliveryOrderServiceType,
    /// IsDeleted attribute of order type.
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    /// External system revision number.
    #[serde(
        rename = "externalRevision",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_revision: Option<Option<i64>>,
    /// IsDefault attribute of order type.
    #[serde(
        rename = "isDefault",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_default: Option<Option<bool>>,
}

impl DeliveryOrderType {
    /// Order type.
    pub fn new(
        id: uuid::Uuid,
        name: String,
        order_service_type: models::DeliveryOrderServiceType,
    ) -> DeliveryOrderType {
        DeliveryOrderType {
            id,
            name,
            order_service_type,
            is_deleted: None,
            external_revision: None,
            is_default: None,
        }
    }
}
