/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmployeeInfo : Employee info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmployeeInfo {
    /// Employee ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Name of employee.
    #[serde(
        rename = "firstName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<Option<String>>,
    /// Second name.
    #[serde(
        rename = "middleName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub middle_name: Option<Option<String>>,
    /// Last name.
    #[serde(
        rename = "lastName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<Option<String>>,
    /// Display name.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// Email.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Phone.
    #[serde(
        rename = "phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone: Option<Option<String>>,
    /// Cell phone.
    #[serde(
        rename = "cellPhone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cell_phone: Option<Option<String>>,
}

impl EmployeeInfo {
    /// Employee info.
    pub fn new(id: uuid::Uuid) -> EmployeeInfo {
        EmployeeInfo {
            id,
            first_name: None,
            middle_name: None,
            last_name: None,
            display_name: None,
            email: None,
            phone: None,
            cell_phone: None,
        }
    }
}
