/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetCountersRequest : Get counters request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCountersRequest {
    /// Guest ids.
    #[serde(rename = "guestIds", skip_serializing_if = "Option::is_none")]
    pub guest_ids: Option<Vec<uuid::Uuid>>,
    /// Periods.
    #[serde(rename = "periods", skip_serializing_if = "Option::is_none")]
    pub periods: Option<Vec<models::EnumsCounter>>,
    ///
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<models::EnumsCounterMetric>>,
    /// Organization id.
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
}

impl GetCountersRequest {
    /// Get counters request.
    pub fn new(organization_id: uuid::Uuid) -> GetCountersRequest {
        GetCountersRequest {
            guest_ids: None,
            periods: None,
            metrics: None,
            organization_id,
        }
    }
}
