/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTransactionsReportByRevisionResponse : Get transactions report by revision
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionsReportByRevisionResponse {
    /// Transactions.
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<models::TransportTransactionsReportItem>>,
    /// Last known transaction revision.
    #[serde(rename = "lastRevision", skip_serializing_if = "Option::is_none")]
    pub last_revision: Option<i64>,
    /// Last known transaction id.
    #[serde(
        rename = "lastTransactionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_transaction_id: Option<Option<uuid::Uuid>>,
    /// Page size.
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
}

impl GetTransactionsReportByRevisionResponse {
    /// Get transactions report by revision
    pub fn new() -> GetTransactionsReportByRevisionResponse {
        GetTransactionsReportByRevisionResponse {
            transactions: None,
            last_revision: None,
            last_transaction_id: None,
            page_size: None,
        }
    }
}
