/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPersonalSessionInfoResponse : Personal session info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPersonalSessionInfoResponse {
    /// Operation ID.
    #[serde(rename = "correlationId")]
    pub correlation_id: uuid::Uuid,
    /// Is personal session opened.
    #[serde(
        rename = "isSessionOpened",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_session_opened: Option<Option<bool>>,
    /// Error details.
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
}

impl GetPersonalSessionInfoResponse {
    /// Personal session info
    pub fn new(correlation_id: uuid::Uuid) -> GetPersonalSessionInfoResponse {
        GetPersonalSessionInfoResponse {
            correlation_id,
            is_session_opened: None,
            error: None,
        }
    }
}
