/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketingCampaignActionConditionBindingInfo : Marketing campaign binding info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketingCampaignActionConditionBindingInfo {
    /// Id.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<uuid::Uuid>>,
    /// Loyalty processing stop after successful execution of binding. So means order of bindings affects.
    #[serde(
        rename = "stopFurtherExecution",
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_further_execution: Option<bool>,
    /// Marketing actions.
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<models::MarketingCampaignSettingsInfo>>,
    /// Marketing conditions.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<models::MarketingCampaignSettingsInfo>>,
}

impl MarketingCampaignActionConditionBindingInfo {
    /// Marketing campaign binding info.
    pub fn new() -> MarketingCampaignActionConditionBindingInfo {
        MarketingCampaignActionConditionBindingInfo {
            id: None,
            stop_further_execution: None,
            actions: None,
            conditions: None,
        }
    }
}
