/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotActivatedCoupon : Not activated coupon.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotActivatedCoupon {
    /// Id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Number. Can be null.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    /// Series name. Can be null.
    #[serde(rename = "seriesName", skip_serializing_if = "Option::is_none")]
    pub series_name: Option<String>,
    /// Series id.
    #[serde(rename = "seriesId", skip_serializing_if = "Option::is_none")]
    pub series_id: Option<uuid::Uuid>,
}

impl NotActivatedCoupon {
    /// Not activated coupon.
    pub fn new() -> NotActivatedCoupon {
        NotActivatedCoupon {
            id: None,
            number: None,
            series_name: None,
            series_id: None,
        }
    }
}
