/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenPersonalSessionRequest : Open personal session request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenPersonalSessionRequest {
    /// Organization ID.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    /// Delivery group ID.                Can be obtained by `/api/1/terminal_groups` operation.
    #[serde(rename = "terminalGroupId")]
    pub terminal_group_id: uuid::Uuid,
    /// Employee ID.
    #[serde(rename = "employeeId")]
    pub employee_id: uuid::Uuid,
    /// Employee role ID.                Must be null if the restaurant doesn't use roles, otherwise not-null role must be specified.
    #[serde(
        rename = "roleId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role_id: Option<Option<uuid::Uuid>>,
}

impl OpenPersonalSessionRequest {
    /// Open personal session request.
    pub fn new(
        organization_id: uuid::Uuid,
        terminal_group_id: uuid::Uuid,
        employee_id: uuid::Uuid,
    ) -> OpenPersonalSessionRequest {
        OpenPersonalSessionRequest {
            organization_id,
            terminal_group_id,
            employee_id,
            role_id: None,
        }
    }
}
