/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderItemType : Flag that determines dish linkage with modifiers scheme.
/// Flag that determines dish linkage with modifiers scheme.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderItemType {
    #[serde(rename = "Product")]
    Product,
    #[serde(rename = "Compound")]
    Compound,
}

impl std::fmt::Display for OrderItemType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Product => write!(f, "Product"),
            Self::Compound => write!(f, "Compound"),
        }
    }
}

impl Default for OrderItemType {
    fn default() -> OrderItemType {
        Self::Product
    }
}
