/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderOrganizationSettings : Organization settings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderOrganizationSettings {
    /// Organization ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Determines whether organization prices include VAT.                Available if `VAT` requested.
    #[serde(
        rename = "pricesVatInclusive",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub prices_vat_inclusive: Option<Option<bool>>,
    /// Determines whether organization loyalty discounts affects VAT.                > Working only if \"pricesVatInclusive\" = false                Available if `VAT` requested.
    #[serde(
        rename = "loyaltyDiscountAffectsVat",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub loyalty_discount_affects_vat: Option<Option<bool>>,
    /// RMS version.                Available if `Version` requested.
    #[serde(
        rename = "version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub version: Option<Option<String>>,
    /// Address format type.                Available if `AddressFormatType` requested.
    #[serde(
        rename = "addressFormatType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub address_format_type: Option<Option<models::OrderAddressFormatType>>,
    /// If the store allows orders for anonymous guests, then it is not necessary to transfer  information about the guest as part of the delivery order. You can only transfer  the phone number and optionally name of the guest, which will not be stored in the guest base  and will only be used for the delivery of a current delivery order.                Available if `IsAnonymousGuestsAllowed` requested.
    #[serde(
        rename = "isAnonymousGuestsAllowed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_anonymous_guests_allowed: Option<Option<bool>>,
    /// Organization name.                Available if `Name` requested.
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// Country.                Available if `Country` requested.
    #[serde(
        rename = "country",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country: Option<Option<String>>,
    /// Restaurant address.                Available if `RestaurantAddress` requested.
    #[serde(
        rename = "restaurantAddress",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub restaurant_address: Option<Option<String>>,
    /// Latitude.                Available if `Latitude` requested.
    #[serde(
        rename = "latitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub latitude: Option<Option<f64>>,
    /// Longitude.                Available if `Longitude` requested.
    #[serde(
        rename = "longitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub longitude: Option<Option<f64>>,
    /// Regional setting \"Use the UAE Addressing System\".                Available if `UseUaeAddressingSystem` requested.
    #[serde(
        rename = "useUaeAddressingSystem",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub use_uae_addressing_system: Option<Option<bool>>,
    /// Country dialing code.                Available if `CountryPhoneCode` requested.
    #[serde(
        rename = "countryPhoneCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country_phone_code: Option<Option<String>>,
    /// Require mandatory marketing source input when creating a delivery.                Available if `MarketingSourceRequiredInDelivery` requested.
    #[serde(
        rename = "marketingSourceRequiredInDelivery",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub marketing_source_required_in_delivery: Option<Option<bool>>,
    /// Default delivery city.                Available if `DefaultDeliveryCityId` requested.
    #[serde(
        rename = "defaultDeliveryCityId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_delivery_city_id: Option<Option<uuid::Uuid>>,
    /// Delivery cities.                Available if `DeliveryCityIds` requested.
    #[serde(
        rename = "deliveryCityIds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery_city_ids: Option<Option<Vec<uuid::Uuid>>>,
    /// Delivery type.                Available if `DeliveryServiceType` requested.
    #[serde(
        rename = "deliveryServiceType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery_service_type: Option<Option<models::OrderDeliverySettingsServiceType>>,
    /// Delivery order payment settings.                Available if `DeliveryOrderPaymentSettings` requested.
    #[serde(
        rename = "deliveryOrderPaymentSettings",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery_order_payment_settings: Option<Option<models::OrderDeliveryOrderPaymentSettings>>,
    /// Default payment type for CallCenter.                Available if `DefaultCallCenterPaymentTypeId` requested.
    #[serde(
        rename = "defaultCallCenterPaymentTypeId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_call_center_payment_type_id: Option<Option<uuid::Uuid>>,
    /// Allow text comments for order items (in all restaurant sections).                Available if `OrderItemCommentEnabled` requested.
    #[serde(
        rename = "orderItemCommentEnabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_item_comment_enabled: Option<Option<bool>>,
    /// Determines whether to use delivery confirmation.                Available if `IsConfirmationEnabled` requested.
    #[serde(
        rename = "isConfirmationEnabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_confirmation_enabled: Option<Option<bool>>,
    /// Confirm orders time interval.                Available if `ConfirmAllowedIntervalInMinutes` requested.
    #[serde(
        rename = "confirmAllowedIntervalInMinutes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub confirm_allowed_interval_in_minutes: Option<Option<i32>>,
    /// Available address lookup services.                Available if `AddressLookup` requested.
    #[serde(
        rename = "addressLookup",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub address_lookup: Option<Option<Vec<models::AddressHintsServiceType>>>,
    /// Determines whether the organization use a business hours and mapping settings.
    #[serde(
        rename = "useBusinessHoursAndMapping",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub use_business_hours_and_mapping: Option<Option<bool>>,
    /// ISO currency code (for example: RUB, USD, EUR).
    #[serde(
        rename = "currencyIsoName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency_iso_name: Option<Option<String>>,
    /// Organization`s external data.
    #[serde(
        rename = "externalData",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_data: Option<Option<Vec<models::ExternalData>>>,
}

impl OrderOrganizationSettings {
    /// Organization settings.
    pub fn new(id: uuid::Uuid) -> OrderOrganizationSettings {
        OrderOrganizationSettings {
            id,
            prices_vat_inclusive: None,
            loyalty_discount_affects_vat: None,
            version: None,
            address_format_type: None,
            is_anonymous_guests_allowed: None,
            name: None,
            country: None,
            restaurant_address: None,
            latitude: None,
            longitude: None,
            use_uae_addressing_system: None,
            country_phone_code: None,
            marketing_source_required_in_delivery: None,
            default_delivery_city_id: None,
            delivery_city_ids: None,
            delivery_service_type: None,
            delivery_order_payment_settings: None,
            default_call_center_payment_type_id: None,
            order_item_comment_enabled: None,
            is_confirmation_enabled: None,
            confirm_allowed_interval_in_minutes: None,
            address_lookup: None,
            use_business_hours_and_mapping: None,
            currency_iso_name: None,
            external_data: None,
        }
    }
}
