/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderOrganizationSettingsParameters : Type of organization settings.
/// Type of organization settings.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderOrganizationSettingsParameters {
    #[serde(rename = "PricesVatInclusive")]
    PricesVatInclusive,
    #[serde(rename = "LoyaltyDiscountAffectsVat")]
    LoyaltyDiscountAffectsVat,
    #[serde(rename = "Version")]
    Version,
    #[serde(rename = "AddressFormatType")]
    AddressFormatType,
    #[serde(rename = "IsAnonymousGuestsAllowed")]
    IsAnonymousGuestsAllowed,
    #[serde(rename = "Name")]
    Name,
    #[serde(rename = "Country")]
    Country,
    #[serde(rename = "RestaurantAddress")]
    RestaurantAddress,
    #[serde(rename = "Latitude")]
    Latitude,
    #[serde(rename = "Longitude")]
    Longitude,
    #[serde(rename = "UseUaeAddressingSystem")]
    UseUaeAddressingSystem,
    #[serde(rename = "CountryPhoneCode")]
    CountryPhoneCode,
    #[serde(rename = "MarketingSourceRequiredInDelivery")]
    MarketingSourceRequiredInDelivery,
    #[serde(rename = "DefaultDeliveryCityId")]
    DefaultDeliveryCityId,
    #[serde(rename = "DeliveryCityIds")]
    DeliveryCityIds,
    #[serde(rename = "DeliveryServiceType")]
    DeliveryServiceType,
    #[serde(rename = "DefaultCallCenterPaymentTypeId")]
    DefaultCallCenterPaymentTypeId,
    #[serde(rename = "OrderItemCommentEnabled")]
    OrderItemCommentEnabled,
    #[serde(rename = "IsConfirmationEnabled")]
    IsConfirmationEnabled,
    #[serde(rename = "ConfirmAllowedIntervalInMinutes")]
    ConfirmAllowedIntervalInMinutes,
    #[serde(rename = "AddressLookup")]
    AddressLookup,
    #[serde(rename = "UseBusinessHoursAndMapping")]
    UseBusinessHoursAndMapping,
    #[serde(rename = "DeliveryOrderPaymentSettings")]
    DeliveryOrderPaymentSettings,
    #[serde(rename = "CurrencyIsoName")]
    CurrencyIsoName,
}

impl std::fmt::Display for OrderOrganizationSettingsParameters {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PricesVatInclusive => write!(f, "PricesVatInclusive"),
            Self::LoyaltyDiscountAffectsVat => write!(f, "LoyaltyDiscountAffectsVat"),
            Self::Version => write!(f, "Version"),
            Self::AddressFormatType => write!(f, "AddressFormatType"),
            Self::IsAnonymousGuestsAllowed => write!(f, "IsAnonymousGuestsAllowed"),
            Self::Name => write!(f, "Name"),
            Self::Country => write!(f, "Country"),
            Self::RestaurantAddress => write!(f, "RestaurantAddress"),
            Self::Latitude => write!(f, "Latitude"),
            Self::Longitude => write!(f, "Longitude"),
            Self::UseUaeAddressingSystem => write!(f, "UseUaeAddressingSystem"),
            Self::CountryPhoneCode => write!(f, "CountryPhoneCode"),
            Self::MarketingSourceRequiredInDelivery => {
                write!(f, "MarketingSourceRequiredInDelivery")
            }
            Self::DefaultDeliveryCityId => write!(f, "DefaultDeliveryCityId"),
            Self::DeliveryCityIds => write!(f, "DeliveryCityIds"),
            Self::DeliveryServiceType => write!(f, "DeliveryServiceType"),
            Self::DefaultCallCenterPaymentTypeId => write!(f, "DefaultCallCenterPaymentTypeId"),
            Self::OrderItemCommentEnabled => write!(f, "OrderItemCommentEnabled"),
            Self::IsConfirmationEnabled => write!(f, "IsConfirmationEnabled"),
            Self::ConfirmAllowedIntervalInMinutes => write!(f, "ConfirmAllowedIntervalInMinutes"),
            Self::AddressLookup => write!(f, "AddressLookup"),
            Self::UseBusinessHoursAndMapping => write!(f, "UseBusinessHoursAndMapping"),
            Self::DeliveryOrderPaymentSettings => write!(f, "DeliveryOrderPaymentSettings"),
            Self::CurrencyIsoName => write!(f, "CurrencyIsoName"),
        }
    }
}

impl Default for OrderOrganizationSettingsParameters {
    fn default() -> OrderOrganizationSettingsParameters {
        Self::PricesVatInclusive
    }
}
