/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RejectItem : Rejected item info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RejectItem {
    /// Terminal group ID.                Can be obtained by `/api/1/terminal_groups` operation.
    #[serde(rename = "terminalGroupId", deserialize_with = "Option::deserialize")]
    pub terminal_group_id: Option<uuid::Uuid>,
    /// Organization ID.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationId", deserialize_with = "Option::deserialize")]
    pub organization_id: Option<uuid::Uuid>,
    /// Delivery zone name which this TerminalGroupId belongs to.
    #[serde(
        rename = "zone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub zone: Option<Option<String>>,
    /// Reject cause code.
    #[serde(rename = "rejectCode")]
    pub reject_code: models::DeliveryRestrictionRejectCode,
    /// Reject hint.
    #[serde(rename = "rejectHint")]
    pub reject_hint: String,
    /// Reject additional information.
    #[serde(
        rename = "rejectItemData",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reject_item_data: Option<Option<Box<models::RejectItemData>>>,
}

impl RejectItem {
    /// Rejected item info.
    pub fn new(
        terminal_group_id: Option<uuid::Uuid>,
        organization_id: Option<uuid::Uuid>,
        reject_code: models::DeliveryRestrictionRejectCode,
        reject_hint: String,
    ) -> RejectItem {
        RejectItem {
            terminal_group_id,
            organization_id,
            zone: None,
            reject_code,
            reject_hint,
            reject_item_data: None,
        }
    }
}
