/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestCreateOrderCombo : Combo in order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestCreateOrderCombo {
    /// Combo ID.  MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid().
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Name of combo.
    #[serde(rename = "name")]
    pub name: String,
    /// Quantity.
    #[serde(rename = "amount")]
    pub amount: i32,
    /// Price of one combo.
    #[serde(rename = "price")]
    pub price: f64,
    /// Combo validity ID.
    #[serde(rename = "sourceId")]
    pub source_id: uuid::Uuid,
    /// Card program ID.   > Allowed from version `7.6.1`.
    #[serde(rename = "programId", skip_serializing_if = "Option::is_none")]
    pub program_id: Option<uuid::Uuid>,
    /// Size ID. Required if combo has a size scale.   > Allowed from version `8.5.6`.
    #[serde(
        rename = "sizeId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub size_id: Option<Option<uuid::Uuid>>,
}

impl RequestCreateOrderCombo {
    /// Combo in order.
    pub fn new(
        id: uuid::Uuid,
        name: String,
        amount: i32,
        price: f64,
        source_id: uuid::Uuid,
    ) -> RequestCreateOrderCombo {
        RequestCreateOrderCombo {
            id,
            name,
            amount,
            price,
            source_id,
            program_id: None,
            size_id: None,
        }
    }
}
