/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestCreateOrderAddressCity : Order delivery address.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestCreateOrderAddressCity {
    /// Address line 1.  Contains the primary address information.   > Allowed from version `8.7.6`.
    #[serde(rename = "line1")]
    pub line1: String,
    /// Apartment.
    #[serde(
        rename = "flat",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub flat: Option<Option<String>>,
    /// Entrance.
    #[serde(
        rename = "entrance",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub entrance: Option<Option<String>>,
    /// Floor.
    #[serde(
        rename = "floor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub floor: Option<Option<String>>,
    /// Intercom.
    #[serde(
        rename = "doorphone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub doorphone: Option<Option<String>>,
    /// Delivery area ID.
    #[serde(
        rename = "regionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub region_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl RequestCreateOrderAddressCity {
    /// Order delivery address.
    pub fn new(line1: String, r#type: String) -> RequestCreateOrderAddressCity {
        RequestCreateOrderAddressCity {
            line1,
            flat: None,
            entrance: None,
            floor: None,
            doorphone: None,
            region_id: None,
            r#type,
        }
    }
}
