/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestOrdersByDeliveryDateAndStatusRequest : Request for information about orders.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestOrdersByDeliveryDateAndStatusRequest {
    /// Organization ID for which an order search will be performed.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationIds")]
    pub organization_ids: Vec<uuid::Uuid>,
    /// Order delivery date (Local for delivery terminal). Lower limit.                The guaranteed order availability  is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
    #[serde(rename = "deliveryDateFrom")]
    pub delivery_date_from: String,
    /// Order delivery date (Local for delivery terminal). Upper limit.
    #[serde(
        rename = "deliveryDateTo",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery_date_to: Option<Option<String>>,
    /// Allowed order statuses.
    #[serde(
        rename = "statuses",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub statuses: Option<Option<Vec<models::DeliveryStatus>>>,
    /// Source keys.
    #[serde(
        rename = "sourceKeys",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_keys: Option<Option<Vec<String>>>,
    /// List of driver IDs.
    #[serde(
        rename = "courierIds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub courier_ids: Option<Option<Vec<uuid::Uuid>>>,
}

impl RequestOrdersByDeliveryDateAndStatusRequest {
    /// Request for information about orders.
    pub fn new(
        organization_ids: Vec<uuid::Uuid>,
        delivery_date_from: String,
    ) -> RequestOrdersByDeliveryDateAndStatusRequest {
        RequestOrdersByDeliveryDateAndStatusRequest {
            organization_ids,
            delivery_date_from,
            delivery_date_to: None,
            statuses: None,
            source_keys: None,
            courier_ids: None,
        }
    }
}
