/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestCreateOrderCompoundOrderItemComponent : Item component
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestCreateOrderCompoundOrderItemComponent {
    /// Item ID.
    #[serde(rename = "productId")]
    pub product_id: uuid::Uuid,
    /// Modifiers.
    #[serde(
        rename = "modifiers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub modifiers: Option<Option<Vec<models::RequestCreateOrderModifier>>>,
    /// Price.
    #[serde(
        rename = "price",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub price: Option<Option<f64>>,
    /// Unique identifier of the item in the order.  MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid().  > If sent null, it generates automatically on iikoTransport side.
    #[serde(
        rename = "positionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub position_id: Option<Option<uuid::Uuid>>,
}

impl RequestCreateOrderCompoundOrderItemComponent {
    /// Item component
    pub fn new(product_id: uuid::Uuid) -> RequestCreateOrderCompoundOrderItemComponent {
        RequestCreateOrderCompoundOrderItemComponent {
            product_id,
            modifiers: None,
            price: None,
            position_id: None,
        }
    }
}
