/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReserveCancelReason : Reason why planned event failed.
/// Reason why planned event failed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReserveCancelReason {
    #[serde(rename = "ClientNotAppeared")]
    ClientNotAppeared,
    #[serde(rename = "ClientRefused")]
    ClientRefused,
    #[serde(rename = "Other")]
    Other,
}

impl std::fmt::Display for ReserveCancelReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientNotAppeared => write!(f, "ClientNotAppeared"),
            Self::ClientRefused => write!(f, "ClientRefused"),
            Self::Other => write!(f, "Other"),
        }
    }
}

impl Default for ReserveCancelReason {
    fn default() -> ReserveCancelReason {
        Self::ClientNotAppeared
    }
}
