/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReserveStatus : Describes the status of a reserve or a banquet.
/// Describes the status of a reserve or a banquet.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReserveStatus {
    #[serde(rename = "New")]
    New,
    #[serde(rename = "Started")]
    Started,
    #[serde(rename = "Closed")]
    Closed,
}

impl std::fmt::Display for ReserveStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "New"),
            Self::Started => write!(f, "Started"),
            Self::Closed => write!(f, "Closed"),
        }
    }
}

impl Default for ReserveStatus {
    fn default() -> ReserveStatus {
        Self::New
    }
}
