/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RmsGetDraftResponse : Wrapping object (external) for an order draft.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RmsGetDraftResponse {
    /// Operation ID.
    #[serde(rename = "correlationId")]
    pub correlation_id: uuid::Uuid,
    /// Order draft object.
    #[serde(rename = "order")]
    pub order: Box<models::RmsDeliveryOrderDraft>,
    /// ID of the employee who is currently editing this draft.
    #[serde(rename = "lockedByUser", deserialize_with = "Option::deserialize")]
    pub locked_by_user: Option<uuid::Uuid>,
    /// Organization ID.
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    /// Terminal group ID.
    #[serde(
        rename = "terminalGroupId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub terminal_group_id: Option<Option<uuid::Uuid>>,
    /// Draft creation time (UTC).
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl RmsGetDraftResponse {
    /// Wrapping object (external) for an order draft.
    pub fn new(
        correlation_id: uuid::Uuid,
        order: models::RmsDeliveryOrderDraft,
        locked_by_user: Option<uuid::Uuid>,
        organization_id: uuid::Uuid,
        created_at: String,
    ) -> RmsGetDraftResponse {
        RmsGetDraftResponse {
            correlation_id,
            order: Box::new(order),
            locked_by_user,
            organization_id,
            terminal_group_id: None,
            created_at,
        }
    }
}
