/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SectionSchema : Table layout.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SectionSchema {
    /// Layout width in px.
    #[serde(rename = "width")]
    pub width: i32,
    /// Layout height in px.
    #[serde(rename = "height")]
    pub height: i32,
    /// Collection of restaurant section marks.
    #[serde(rename = "markElements")]
    pub mark_elements: Vec<models::RestaurantSectionMark>,
    /// Collection of restaurant section tables.
    #[serde(rename = "tableElements")]
    pub table_elements: Vec<models::RestaurantSectionTable>,
    /// Collection of restaurant section rectangles.
    #[serde(rename = "rectangleElements")]
    pub rectangle_elements: Vec<models::RestaurantSectionRectangle>,
    /// Collection of restaurant section ellipses.
    #[serde(rename = "ellipseElements")]
    pub ellipse_elements: Vec<models::RestaurantSectionEllipse>,
    /// Last modified time.
    #[serde(rename = "revision")]
    pub revision: i64,
    /// Is schema deleted.
    #[serde(rename = "isDeleted")]
    pub is_deleted: bool,
}

impl SectionSchema {
    /// Table layout.
    pub fn new(
        width: i32,
        height: i32,
        mark_elements: Vec<models::RestaurantSectionMark>,
        table_elements: Vec<models::RestaurantSectionTable>,
        rectangle_elements: Vec<models::RestaurantSectionRectangle>,
        ellipse_elements: Vec<models::RestaurantSectionEllipse>,
        revision: i64,
        is_deleted: bool,
    ) -> SectionSchema {
        SectionSchema {
            width,
            height,
            mark_elements,
            table_elements,
            rectangle_elements,
            ellipse_elements,
            revision,
            is_deleted,
        }
    }
}
