/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleModifierInfo : Modifier details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleModifierInfo {
    /// ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Default quantity.
    #[serde(
        rename = "defaultAmount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_amount: Option<Option<i32>>,
    /// Minimum quantity.
    #[serde(rename = "minAmount")]
    pub min_amount: i32,
    /// Maximum quantity.
    #[serde(rename = "maxAmount")]
    pub max_amount: i32,
    /// Required availability.
    #[serde(
        rename = "required",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub required: Option<Option<bool>>,
    /// Hide if default amount applied. This field is supported since 7.2.4 iikoRMS version.
    #[serde(
        rename = "hideIfDefaultAmount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub hide_if_default_amount: Option<Option<bool>>,
    /// Modifier can be split. This field is supported since 7.2.4 iikoRMS version.
    #[serde(
        rename = "splittable",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub splittable: Option<Option<bool>>,
    /// Free of charge amount. This field is supported since 7.2.4 iikoRMS version.
    #[serde(
        rename = "freeOfChargeAmount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub free_of_charge_amount: Option<Option<i32>>,
}

impl SimpleModifierInfo {
    /// Modifier details.
    pub fn new(id: uuid::Uuid, min_amount: i32, max_amount: i32) -> SimpleModifierInfo {
        SimpleModifierInfo {
            id,
            default_amount: None,
            min_amount,
            max_amount,
            required: None,
            hide_if_default_amount: None,
            splittable: None,
            free_of_charge_amount: None,
        }
    }
}
