/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Street : Street DTO in iikoRMS
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Street {
    /// ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Name.
    #[serde(rename = "name")]
    pub name: String,
    /// External system revision No.
    #[serde(
        rename = "externalRevision",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_revision: Option<Option<i64>>,
    /// ID in classifier, e.g., address database.
    #[serde(
        rename = "classifierId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub classifier_id: Option<Option<String>>,
    /// Is-Deleted attribute.
    #[serde(rename = "isDeleted")]
    pub is_deleted: bool,
}

impl Street {
    /// Street DTO in iikoRMS
    pub fn new(id: uuid::Uuid, name: String, is_deleted: bool) -> Street {
        Street {
            id,
            name,
            external_revision: None,
            classifier_id: None,
            is_deleted,
        }
    }
}
