/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TipsType : Tips type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TipsType {
    /// Tips type ID.                Can be obtained by `/api/1/tips_types` operation.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Tips type name.
    #[serde(rename = "name")]
    pub name: String,
    /// Supported organizations IDs.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationIds")]
    pub organization_ids: Vec<uuid::Uuid>,
    /// Supported order service types.
    #[serde(rename = "orderServiceTypes")]
    pub order_service_types: Vec<models::DeliveryOrderServiceType>,
    /// Supported payment types IDs.
    #[serde(rename = "paymentTypesIds")]
    pub payment_types_ids: Vec<uuid::Uuid>,
}

impl TipsType {
    /// Tips type.
    pub fn new(
        id: uuid::Uuid,
        name: String,
        organization_ids: Vec<uuid::Uuid>,
        order_service_types: Vec<models::DeliveryOrderServiceType>,
        payment_types_ids: Vec<uuid::Uuid>,
    ) -> TipsType {
        TipsType {
            id,
            name,
            organization_ids,
            order_service_types,
            payment_types_ids,
        }
    }
}
