/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransportModifierGroupDto {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::TransportModifierItemDto>>,
    /// Modifiers group name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Modifiers group description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Box<models::ModifierRestrictionsDto>>,
    /// Whether the modifier can be splitted
    #[serde(rename = "canBeDivided", skip_serializing_if = "Option::is_none")]
    pub can_be_divided: Option<bool>,
    /// Modifiers group id
    #[serde(rename = "itemGroupId", skip_serializing_if = "Option::is_none")]
    pub item_group_id: Option<uuid::Uuid>,
    /// Whether child modifiers can have their own restrictions, or only group ones
    #[serde(
        rename = "childModifiersHaveMinMaxRestrictions",
        skip_serializing_if = "Option::is_none"
    )]
    pub child_modifiers_have_min_max_restrictions: Option<bool>,
    /// Modifiers group code
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<String>,
}

impl TransportModifierGroupDto {
    pub fn new() -> TransportModifierGroupDto {
        TransportModifierGroupDto {
            items: None,
            name: None,
            description: None,
            restrictions: None,
            can_be_divided: None,
            item_group_id: None,
            child_modifiers_have_min_max_restrictions: None,
            sku: None,
        }
    }
}
