/*
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateWebHookSettingsRequest : Request to add or update webhooks settings for listed api logins of the specified organization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebHookSettingsRequest {
    /// Organization UOC Id.                Can be obtained by `/api/1/organizations` operation.
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    /// Webhook handler url.
    #[serde(rename = "webHooksUri")]
    pub web_hooks_uri: String,
    /// Authorization token to pass to the webhook handler.
    #[serde(
        rename = "authToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub auth_token: Option<Option<String>>,
    /// Webhooks filter.
    #[serde(
        rename = "webHooksFilter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_hooks_filter: Option<Option<Box<models::WebHooksFilter>>>,
}

impl UpdateWebHookSettingsRequest {
    /// Request to add or update webhooks settings for listed api logins of the specified organization.
    pub fn new(organization_id: uuid::Uuid, web_hooks_uri: String) -> UpdateWebHookSettingsRequest {
        UpdateWebHookSettingsRequest {
            organization_id,
            web_hooks_uri,
            auth_token: None,
            web_hooks_filter: None,
        }
    }
}
